"""Sample data matching harga v9 backend schema. Malaysian government procurement."""

SAMPLE_DATA = {
    "tenders": {
        "tenders": [
            {
                "id": "EPE-2026-04821",
                "title": "Bekalan & Penghantaran Alat Tulis Pejabat Kementerian Pendidikan",
                "portal": "ePerolehan",
                "reference": "GEP-RFP-2026-0482",
                "status": "open",
                "deadline": "2026-08-02T17:00:00Z",
                "amount": 185000.00,
                "issuer": "Kementerian Pendidikan Malaysia",
                "buyer": None,
            },
            {
                "id": "EPE-2026-04790",
                "title": "Perkhidmatan Penyelenggaraan Sistem HVAC Bangunan Kerajaan",
                "portal": "ePerolehan",
                "reference": "GEP-RFQ-2026-0479",
                "status": "open",
                "deadline": "2026-07-30T17:00:00Z",
                "amount": 420000.00,
                "issuer": "Jabatan Kerja Raya",
                "buyer": None,
            },
            {
                "id": "FSH-2026-01547",
                "title": "Kerja-kerja Menaiktaraf Jalan Daerah Hulu Langat Fasa 3",
                "portal": "ForSAH",
                "reference": "FSH-T-2026-1547",
                "status": "open",
                "deadline": "2026-08-15T17:00:00Z",
                "amount": 2750000.00,
                "issuer": "Majlis Perbandaran Hulu Langat",
                "buyer": None,
            },
            {
                "id": "ETI-2026-00312",
                "title": "Pembinaan Jambatan Pejalan Kaki Taman Melawati",
                "portal": "eTimad",
                "reference": "ETI-2026-00312",
                "status": "open",
                "deadline": "2026-08-10T17:00:00Z",
                "amount": 890000.00,
                "issuer": "Majlis Bandaraya Gombak Selangor",
                "buyer": None,
            },
            {
                "id": "EPE-2026-04755",
                "title": "Bekalan Peralatan Keselamatan ICT Jabatan Perdana Menteri",
                "portal": "ePerolehan",
                "reference": "GEP-RFQ-2026-0475",
                "status": "open",
                "deadline": "2026-07-29T10:00:00Z",
                "amount": 315000.00,
                "issuer": "Jabatan Perdana Menteri",
                "buyer": None,
            },
            {
                "id": "FSH-2026-01520",
                "title": "Perkhidmatan Kawalan Keselamatan Kompleks Sukan Bukit Jalil",
                "portal": "ForSAH",
                "reference": "FSH-T-2026-1520",
                "status": "closed",
                "deadline": "2026-07-20T17:00:00Z",
                "amount": 1200000.00,
                "issuer": "Kementerian Belia dan Sukan",
                "buyer": None,
            },
            {
                "id": "ETI-2026-00298",
                "title": "Kerja Pembersihan & Penyelenggaraan Sungai Klang Fasa 2",
                "portal": "eTimad",
                "reference": "ETI-2026-00298",
                "status": "closed",
                "deadline": "2026-07-15T17:00:00Z",
                "amount": 3400000.00,
                "issuer": "Jabatan Pengairan & Saliran",
                "buyer": None,
            },
            {
                "id": "EPE-2026-04812",
                "title": "Bekalan Komputer Riba untuk Program Sekolah Digital",
                "portal": "ePerolehan",
                "reference": "GEP-RFQ-2026-0481",
                "status": "open",
                "deadline": "2026-08-05T17:00:00Z",
                "amount": 5200000.00,
                "issuer": "Kementerian Pendidikan Malaysia",
                "buyer": None,
            },
        ],
        "total": 95,
        "limit": 8,
        "offset": 0,
    },

    "bids": {
        "bids": [
            {
                "id": "bid-ct-001",
                "reference": "GEP-RFP-2026-0482",
                "title": "Bekalan Alat Tulis Kementerian Pendidikan",
                "entity_slug": "consurv-technic",
                "status": "active",
                "workflow_phase": "pricing",
                "deadline": "2026-08-02T17:00:00Z",
                "amount": 178500.00,
                "levers": {"markup": 15.0, "overhead": 8.0, "contingency": 3.0, "risk_premium": 0.0},
                "assigned_to": "ahmad",
                "source_tender_id": "EPE-2026-04821",
                "created_at": "2026-07-25T09:15:00Z",
            },
            {
                "id": "bid-ct-002",
                "reference": "GEP-RFQ-2026-0479",
                "title": "Penyelenggaraan HVAC Bangunan Kerajaan",
                "entity_slug": "consurv-technic",
                "status": "submitted",
                "workflow_phase": "submitted",
                "deadline": "2026-07-30T17:00:00Z",
                "amount": 398000.00,
                "levers": {"markup": 12.0, "overhead": 8.0, "contingency": 5.0, "risk_premium": 2.0},
                "assigned_to": "ahmad",
                "source_tender_id": "EPE-2026-04790",
                "created_at": "2026-07-22T14:30:00Z",
            },
            {
                "id": "bid-ds-001",
                "reference": "FSH-T-2026-1547",
                "title": "Menaiktaraf Jalan Hulu Langat Fasa 3",
                "entity_slug": "dyna-segmen",
                "status": "draft",
                "workflow_phase": "pricing",
                "deadline": "2026-08-15T17:00:00Z",
                "amount": None,
                "levers": {"markup": 15.0, "overhead": 8.0, "contingency": 3.0, "risk_premium": 0.0},
                "assigned_to": None,
                "source_tender_id": "FSH-2026-01547",
                "created_at": "2026-07-27T11:00:00Z",
            },
            {
                "id": "bid-dsc-001",
                "reference": "ETI-2026-00312",
                "title": "Jambatan Pejalan Kaki Taman Melawati",
                "entity_slug": "dyna-sche",
                "status": "priced",
                "workflow_phase": "approval",
                "deadline": "2026-08-10T17:00:00Z",
                "amount": 845000.00,
                "levers": {"markup": 18.0, "overhead": 10.0, "contingency": 5.0, "risk_premium": 3.0},
                "assigned_to": "farid",
                "source_tender_id": "ETI-2026-00312",
                "created_at": "2026-07-26T08:45:00Z",
            },
            {
                "id": "bid-ct-003",
                "reference": "FSH-T-2026-1520",
                "title": "Kawalan Keselamatan Bukit Jalil",
                "entity_slug": "consurv-technic",
                "status": "won",
                "workflow_phase": "post_submit",
                "deadline": "2026-07-20T17:00:00Z",
                "amount": 1150000.00,
                "levers": {"markup": 12.0, "overhead": 8.0, "contingency": 3.0, "risk_premium": 0.0},
                "assigned_to": "ahmad",
                "source_tender_id": "FSH-2026-01520",
                "outcome": "won",
                "outcome_at": "2026-07-25T10:00:00Z",
                "created_at": "2026-07-10T16:20:00Z",
            },
            {
                "id": "bid-dom-001",
                "reference": "ETI-2026-00298",
                "title": "Pembersihan Sungai Klang Fasa 2",
                "entity_slug": "dyna-om",
                "status": "lost",
                "workflow_phase": "post_submit",
                "deadline": "2026-07-15T17:00:00Z",
                "amount": 3200000.00,
                "levers": {"markup": 15.0, "overhead": 8.0, "contingency": 3.0, "risk_premium": 0.0},
                "assigned_to": "razak",
                "source_tender_id": "ETI-2026-00298",
                "outcome": "lost",
                "outcome_at": "2026-07-22T14:00:00Z",
                "outcome_competitor": "Syarikat Pembersih Utama Sdn Bhd",
                "outcome_margin_delta": -4.2,
                "created_at": "2026-07-05T10:00:00Z",
            },
            {
                "id": "bid-ct-004",
                "reference": "GEP-RFQ-2026-0475",
                "title": "Peralatan Keselamatan ICT JPM",
                "entity_slug": "consurv-technic",
                "status": "overdue",
                "workflow_phase": "packaging",
                "deadline": "2026-07-29T10:00:00Z",
                "amount": 305000.00,
                "levers": {"markup": 15.0, "overhead": 8.0, "contingency": 3.0, "risk_premium": 0.0},
                "assigned_to": "ahmad",
                "source_tender_id": "EPE-2026-04755",
                "created_at": "2026-07-20T13:00:00Z",
            },
        ],
        "total": 7,
        "limit": 50,
        "offset": 0,
    },

    "entities": {
        "entities": [
            {
                "slug": "consurv-technic",
                "name": "Consurv Technic Sdn Bhd",
                "label": "Consultancy & Survey",
                "notification_channel": "tg:198234",
                "team_leads": ["Ahmad Zaidi", "Siti Nadia"],
                "default_markup": 15.0,
                "default_overhead": 8.0,
                "default_contingency": 3.0,
                "default_risk_premium": 0.0,
            },
            {
                "slug": "dyna-om",
                "name": "Dyna O&M Sdn Bhd",
                "label": "Operations & Maintenance",
                "notification_channel": "tg:198235",
                "team_leads": ["Razak Ibrahim"],
                "default_markup": 15.0,
                "default_overhead": 8.0,
                "default_contingency": 3.0,
                "default_risk_premium": 0.0,
            },
            {
                "slug": "dyna-segmen",
                "name": "Dyna Segmen Sdn Bhd",
                "label": "Electrical & Instrumentation",
                "notification_channel": None,
                "team_leads": ["Hafiz Rahman", "Nurul Ain"],
                "default_markup": 15.0,
                "default_overhead": 8.0,
                "default_contingency": 3.0,
                "default_risk_premium": 0.0,
            },
            {
                "slug": "dyna-sche",
                "name": "Dyna SCHE Sdn Bhd",
                "label": "Scheme & Infrastructure",
                "notification_channel": "tg:198237",
                "team_leads": ["Farid Azman"],
                "default_markup": 15.0,
                "default_overhead": 8.0,
                "default_contingency": 3.0,
                "default_risk_premium": 0.0,
            },
        ],
    },

    "status": {
        "by_status": {
            "active": 2,
            "submitted": 2,
            "draft": 1,
            "priced": 1,
            "won": 2,
            "lost": 1,
            "overdue": 1,
        },
        "by_platform": {
            "ePerolehan": 5,
            "ForSAH": 3,
            "eTimad": 4,
        },
        "by_entity": {
            "consurv-technic": 4,
            "dyna-om": 3,
            "dyna-segmen": 2,
            "dyna-sche": 3,
        },
        "deadlines_today": 1,
        "total_value": 6176500.00,
        "total_bids": 12,
        "pipeline_value": 4026500.00,
        "win_rate": 0.667,
    },
}
